name: pipe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0 # For sending http requests
  path_provider: ^2.1.2 # To handle local storage
  permission_handler: ^10.2.0 # For requesting storage permission on Android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
